[package]
name = "pdf-forensic-editor"
version = "1.0.0"
edition = "2021"
authors = ["Corporate Development Team"]
description = "PDF Document Metadata Standardizer for Corporate Compliance"
license = "MIT" 
repository = "https://github.com/corporate/pdf-standardizer"
readme = "README.md"
keywords = ["pdf", "metadata", "compliance", "standardization"]
categories = ["command-line-utilities", "data-structures"]

[dependencies]
# PDF Processing Core
lopdf = "0.32"
pdf = "0.8"

# CLI and Configuration
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Cryptography and Security
aes = "0.8"  
sha2 = "0.10"
rand = "0.8"

# File System Operations
filetime = "0.2"
chrono = { version = "0.4", features = ["serde"] }

# Error Handling
anyhow = "1.0"
thiserror = "1.0"

# Utilities
base64 = "0.21"
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3.0"
assert_cmd = "2.0"
predicates = "3.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
